### ISSUE TITLE
Reconsider GitHub setup

### ISSUE THREAD

**Issue by arothuis-hu** [arothuis-hu/cisq1-lingo#16]
## Should we prescribe forking? 
Students accidentally submit PRs against this repository and GitHub does not allow removing PRs.

## Should we use public repositories? 
These are necessary for SonarCloud, but allow students to see each other's works.
Because there is intensive feedback and there is another test, there are sufficient corrective measures.
Furthermore, we choose to trust our students.

Perhaps GitHub education offers something in this regard?

**Comment by Hugo-Helder** [comment]
GitHub Classrooms will offer a solution for the first one, unfortunately not for the second. But instead of SonarCloud a local hosted SonarQube instance can be used to circumvent this

**Comment by arothuis-hu** [comment]
Good idea. Does GitHub classroom allow students to fully configure their continuous integration environment (GitHub Actions)? 

We could research whether a non-cloud static analysis tool is easy to use and explain (alternatives: FindBugs, checkstyle, sonarqube). 

For coverage badges, we can use a GitHub Action that reads out the CSV and generates a badge, i.e: https://github.com/arothuis/antlr4-calculator/blob/master/.github/workflows/build.yml#L35-L54 and https://github.com/arothuis/antlr4-calculator/blob/master/pom.xml
Perhaps we can even generate badges for PITest the same way...

**Comment by arothuis-hu** [comment]
As we're moving static analysis and security analysis to another course, there are no limitations to move to GitHub Classrooms -- if GitHub Actions is supported and if we have enough minutes for all our students.

**Comment by rkuijt** [comment]
After some digging I've found that it's pretty hard to make use of static analysis tools and code coverage reporting tools that are provided on a SaaS basis and allow private repositories. Most of these tools are licensed to individuals and so students would need to allow these tools on their accounts. These tools often require access to _all_ repositories on an account so it would be preferable to create a service account for this purpose. Not only would that require quite a complicated process to set-up but it's also not feasible most of the time since these service accounts would not have the Github for Education benefits.

However, Github's beloved competitor (Gitlab), seems to have code coverage and reporting build into their CI/CD solution which comes in the same package. They offer free resources for educational use as well, this may be _very_ worthwhile to investigate. I'll pick this up next week.

**Comment by arothuis-hu** [comment]
For now, we'll use GitHub Classrooms with private repositories, GitHub Actions and workflow artifacts (which are stored for 90 days). Not ideal, but it suffices for now.
